package com.pumpernickel.data.db

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity for the `progress_pictures` table introduced in DB v9.
 *
 * Mirrors the FK + Index shape of [CompletedWorkoutExerciseEntity]: every photo
 * belongs to exactly one [CompletedWorkoutEntity]; deleting a workout cascades
 * to its photos (Phase 17 D-17-08 / D-17-09).
 *
 * The primary key [id] is the **UUID generated upstream**, NOT auto-generated by
 * Room — it doubles as the on-disk filename stem for the JPEG written into
 * `<filesDir>/progress_pics/{id}.jpg` (Phase 17 D-17-05). [relativePath] stores
 * the path relative to the platform-specific photo-vault root so platform code
 * can resolve it consistently across iOS Documents and Android filesDir.
 */
@Entity(
    tableName = "progress_pictures",
    foreignKeys = [ForeignKey(
        entity = CompletedWorkoutEntity::class,
        parentColumns = ["id"],
        childColumns = ["workoutId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index("workoutId")]
)
data class ProgressPictureEntity(
    @PrimaryKey val id: String,        // UUID, also the filename stem (D-17-05)
    val workoutId: Long,
    val relativePath: String,           // "progress_pics/{uuid}.jpg" (D-17-05)
    val capturedAtMillis: Long,
    val sortOrder: Int                  // 0-based per workout, tiebreak when capturedAtMillis ties
)
